# Generated by Django 5.1.1 on 2024-10-02 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("backlog", "0002_alter_backlog_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacklogStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "backlog"),
                            (2, "sprint_term"),
                            (3, "in_progress"),
                            (4, "review"),
                            (5, "completed"),
                            (6, "additional_work"),
                            (7, "archived"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "backlog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="backlog.backlog",
                    ),
                ),
            ],
        ),
    ]
