# Generated by Django 5.1.1 on 2024-10-03 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("backlog_todo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacklogTodoCheck",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("isChecked", models.BooleanField(default=False)),
                (
                    "backlogTodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="backlog_todo.backlogtodo",
                    ),
                ),
            ],
            options={
                "db_table": "backlog_todo_check",
            },
        ),
    ]
