# Generated by Django 5.1.1 on 2024-09-25 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountRoleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roleType", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "account_role_type",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=64)),
                (
                    "roleType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.accountroletype",
                    ),
                ),
            ],
            options={
                "db_table": "account",
            },
        ),
    ]
