# Generated by Django 5.1.1 on 2024-09-26 03:44

from django.db import migrations, models

from account.entity.role_type import RoleType


def create_default_roles(apps, schema_editor):
    AccountRoleType = apps.get_model('account', 'AccountRoleType')

    AccountRoleType.objects.create(roleType=RoleType.ADMIN)
    AccountRoleType.objects.create(roleType=RoleType.NORMAL)

class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountroletype",
            name="roleType",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("NORMAL", "Normal")],
                default="NORMAL",
                max_length=64,
            ),
        ),
        migrations.RunPython(create_default_roles)
    ]
