# Generated by Django 5.1.1 on 2024-10-02 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("backlog", "0002_alter_backlog_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacklogMapNumber",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("map_number", models.IntegerField()),
                (
                    "backlog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_numbers",
                        to="backlog.backlog",
                    ),
                ),
            ],
            options={
                "db_table": "backlog_map_number",
            },
        ),
    ]
