# Generated by Django 5.1.1 on 2024-10-07 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backlog_map_number", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="backlogmapnumber",
            old_name="map_number",
            new_name="mapNumber",
        ),
    ]
