# Generated by Django 5.1.1 on 2024-09-13 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SurveyDocument",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "survey_document",
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "SurveyDocumentID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.surveydocument",
                    ),
                ),
            ],
            options={
                "db_table": "survey",
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("SurveyQuestionNumber", models.IntegerField(default=0)),
                (
                    "SurveyID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="survey.survey"
                    ),
                ),
            ],
            options={
                "db_table": "survey_question",
            },
        ),
        migrations.CreateModel(
            name="SurveySelection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("SurveySelectionNumber", models.IntegerField(default=0)),
                (
                    "SurveyQuestionID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.surveyquestion",
                    ),
                ),
            ],
            options={
                "db_table": "survey_selection",
            },
        ),
        migrations.CreateModel(
            name="SurveyAnswer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "SurveyQuestionID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.surveyquestion",
                    ),
                ),
                (
                    "SurveySelectionID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.surveyselection",
                    ),
                ),
            ],
            options={
                "db_table": "survey_answer",
            },
        ),
    ]
