# Generated by Django 5.1.1 on 2024-09-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="SurveyQuestionSentence",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="surveyselection",
            name="SurveySelectionSentence",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
