# Generated by Django 5.1.1 on 2024-10-10 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0002_rename_writer_resultreport_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultReportModify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modifier', models.CharField(max_length=128)),
                ('modifyDate', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modify', to='report.resultreport')),
            ],
            options={
                'db_table': 'result_report_modify',
            },
        ),
    ]
