# Generated by Django 5.1.1 on 2024-09-30 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("backlog", "0002_alter_backlog_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacklogDomain",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "backlog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="backlog.backlog",
                    ),
                ),
            ],
            options={
                "db_table": "backlog_domain",
            },
        ),
    ]
