# Generated by Django 5.1.1 on 2024-10-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=128)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'result_report',
            },
        ),
    ]
