# Generated by Django 5.1.1 on 2024-10-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultreport',
            old_name='writer',
            new_name='creator',
        ),
    ]
