# Generated by Django 5.1.1 on 2024-10-11 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0002_rename_writer_resultreport_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultReportTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='report.resultreport')),
            ],
            options={
                'db_table': 'report_title',
            },
        ),
    ]
