# Generated by Django 5.1.1 on 2024-10-08 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("WRITING", "Writing"), ("SELECTION", "Selection")],
                        default="SELECTION",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "db_table": "review_list",
            },
        ),
        migrations.CreateModel(
            name="SelectionReview",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("writer", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=128)),
                (
                    "using",
                    models.IntegerField(
                        choices=[
                            (1, "ONE"),
                            (2, "TWO"),
                            (3, "THREE"),
                            (4, "FOUR"),
                            (5, "FIVE"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "speed",
                    models.IntegerField(
                        choices=[
                            (1, "ONE"),
                            (2, "TWO"),
                            (3, "THREE"),
                            (4, "FOUR"),
                            (5, "FIVE"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "design",
                    models.IntegerField(
                        choices=[
                            (1, "ONE"),
                            (2, "TWO"),
                            (3, "THREE"),
                            (4, "FOUR"),
                            (5, "FIVE"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "quality",
                    models.IntegerField(
                        choices=[
                            (1, "ONE"),
                            (2, "TWO"),
                            (3, "THREE"),
                            (4, "FOUR"),
                            (5, "FIVE"),
                        ],
                        default=1,
                    ),
                ),
                ("feedback", models.TextField()),
                ("regDate", models.DateTimeField(auto_now_add=True)),
                ("updDate", models.DateTimeField(auto_now=True)),
                (
                    "listId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selection_review",
                        to="review.reviewlist",
                    ),
                ),
            ],
            options={
                "db_table": "selection_review",
            },
        ),
        migrations.CreateModel(
            name="WritingReview",
            fields=[
                ("reviewId", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=128)),
                ("writer", models.CharField(max_length=32)),
                ("content", models.TextField()),
                ("image", models.CharField(max_length=100, null=True)),
                ("regDate", models.DateTimeField(auto_now_add=True)),
                ("updDate", models.DateTimeField(auto_now=True)),
                (
                    "listId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writing_review",
                        to="review.reviewlist",
                    ),
                ),
            ],
            options={
                "db_table": "writing_review",
            },
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
